/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Finda.view;
import FindaController.AnggotaController;
/**
 *
 * @author LENOVO
 */
public class FormAnggota extends javax.swing.JFrame {

    /**
     * Creates new form FormAnggota
     */
    AnggotaController controller;
    public FormAnggota() {
        initComponents();
        controller = new AnggotaController(this);
        controller.bersihForm();
        controller.TampilData();
    }
public javax.swing.JTextField getTxtnobp(){
    return Txtnobp;
}
 public javax.swing.JTextField getTxtAlamat(){
     return TxtAlamat;
 }
  public javax.swing.JTextField getTxtNama(){
      return TxtNama;
  }
   public javax.swing.JTable getTblAnggota(){
       return TblAnggota;
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TxtAlamat = new javax.swing.JTextField();
        Txtnobp = new javax.swing.JTextField();
        TxtNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnCancel = new javax.swing.JButton();
        BtnInsert = new javax.swing.JButton();
        BtnUpdate = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblAnggota = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Anggota");
        getContentPane().setLayout(null);

        jLabel1.setText("Alamat");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 80, 70, 30);

        TxtAlamat.setText("jTextField1");
        getContentPane().add(TxtAlamat);
        TxtAlamat.setBounds(120, 80, 330, 30);

        Txtnobp.setText("jTextField1");
        Txtnobp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtnobpActionPerformed(evt);
            }
        });
        getContentPane().add(Txtnobp);
        Txtnobp.setBounds(120, 20, 330, 30);

        TxtNama.setText("jTextField1");
        getContentPane().add(TxtNama);
        TxtNama.setBounds(120, 50, 330, 30);

        jLabel2.setText("nobp");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 20, 70, 30);

        jLabel3.setText("Nama");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 50, 70, 30);

        BtnCancel.setText("Cancel");
        getContentPane().add(BtnCancel);
        BtnCancel.setBounds(320, 130, 79, 29);

        BtnInsert.setText("Insert");
        BtnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(BtnInsert);
        BtnInsert.setBounds(20, 130, 73, 29);

        BtnUpdate.setText("Update");
        getContentPane().add(BtnUpdate);
        BtnUpdate.setBounds(120, 130, 83, 29);

        BtnDelete.setText("Delete");
        getContentPane().add(BtnDelete);
        BtnDelete.setBounds(220, 130, 77, 29);

        TblAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nobp", "Nama", "Alamat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TblAnggota);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 170, 440, 130);

        setSize(new java.awt.Dimension(482, 420));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInsertActionPerformed
        // TODO add your handling code here:
         controller.save();
        controller.TampilData();
        controller.bersihForm();
    }//GEN-LAST:event_BtnInsertActionPerformed

    private void TxtnobpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtnobpActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_TxtnobpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAnggota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancel;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnInsert;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JTable TblAnggota;
    private javax.swing.JTextField TxtAlamat;
    private javax.swing.JTextField TxtNama;
    private javax.swing.JTextField Txtnobp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
